method: hnn

data:
  cut_start_seconds_train: 0.0
  cut_start_seconds_val: 0.0
  reduce_time: true
  reduction_factor: 5
  train_series_dir: Data_Gen/npz_exports_td_burnin_trimmed

model:
  rho: 1.0
  D: 1.0
  structural_mass: 16.79
  Ca: 1.0
  k: 1218.0
  damping_c: 1e-4

training:
  batch_size: 1024
  max_grad_norm: 20.0
  epochs: 2000

optim:
  lr: 0.001
  optimizer: adam
  weight_decay: 0.0
  use_lr_scheduler: true
  scheduler:
    max_lr: 0.001
    decay_rate: 0.99
    warmup_fraction: 0.05
    min_lr: 0.0001
    scheduler_type: cosine

loss:
  mean_reg: 0.0
  mean_reg_norm: l1
  rollout_det_weight: 0.0
  rollout_det_steps: 0
  rollout_det_steps_final: 0
  rollout_det_steps_warmup_epochs: 0
  rollout_det_batch_size: 0
  use_force_data_loss: false
  force_data_weight: 0.0
  use_gradnorm: false
  gradnorm_alpha: 0.9
  gradnorm_min_weight: 0.001
  gradnorm_max_weight: 1000.0

runtime:
  device: cuda
  num_workers: 4

precision:
  use_tf32: false
  use_amp: false
  amp_dtype: bf16

compile:
  use_compile: false
  compile_mode: reduce-overhead

monitoring:
  validate_every_epochs: 50
  validation_samples_per_ur: 2
  final_rollout_all_validation: true
  log_every_epochs: 10
  print_every_epochs: 50
  log_component_grad_norms: false
  async_validation: true
  async_validation_device: cpu
  async_validation_num_workers: 0
  async_validation_num_threads: 1
  async_validation_max_concurrent: 6

logging:
  run_dir_root: logs
  run_name: null
  append_timestamp: true

hnn:
  td_parameter_model: global_delta
  td_cv: 1.2
  td_cd: 1.1
  td_ca: 1.0
  td_fhat0: 0.18
  td_fhat_min: 0.11
  td_fhat_max: 0.26
  td_n_memory: 500
  td_mass_source: dry

pinn: {}
